version: "3.3"

services:
  docker-tag1:
    image: ${IMAGE_ID}
    networks:
      - docker-tag-network
    tty: true
    privileged: true

  docker-tag2:
    image: ${IMAGE_ID}
    networks:
      - docker-tag-network
    tty: true
    privileged: true
  
  docker-tag-rep:
    image: registry
    networks:
      - docker-tag-network
    tty: true

networks:
  docker-tag-network:
    driver: bridge
