version: "3.3"

services:
  docker-tag1:
    image: test_tag:1.0
    networks:
      - docker-tag-network
    tty: true

  docker-tag2:
    image: test_tag:1.0
    networks:
      - docker-tag-network
    tty: true
  
  docker-tag-rep:
    image: registry
    networks:
      - docker-tag-network
    tty: true

networks:
  docker-tag-network:
    driver: bridge
