version: '3.3'

services:
  docker-network-nginx:
    build: .
    ports:
      - "8080:80"
      - "8081:3000"
    depends_on:
      - docker-network-tomcat
    networks: 
      - docker-sample-network

  docker-network-tomcat:
    image: tomcat
    networks: 
      - docker-sample-network

networks:
  docker-sample-network:
    driver: bridge

 
 
