apiVersion: v1
kind: Service
metadata:
  name: docker-network-service
spec:
  type: NodePort
  # type: LoadBalancer
  selector:
    app: docker-network
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 3000
