version: "3"

services:
    
  local-redis:
    image: redis
    container_name:
      rails-redis
  
  local-rails:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - local-redis
    env_file:
      - env_file.env
    container_name:
      rails-rails
    command:
      bundle exec rails s -b 0.0.0.0
      